# This file provides instructions for packaging.

`MooseX-ABCD`
	perl_version_from m`MooseX::ABCD`;
	version_from      m`MooseX::ABCD`;
	readme_from       m`MooseX::ABCD`;
	requires          p`MooseX::ABC`;
	requires          p`namespace::autoclean`;
	test_requires     p`Test::More 0.61`;
	test_requires     p`Test::Fatal`.

